---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jameslendrem.
--- DateTime: 21/03/2024 20:50
---

class("Event").extends();

function Event:init(name)
    self.name = name;
end