---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jameslendrem.
--- DateTime: 22/03/2024 19:00
---

import 'listener'

class('InputController').extends('Listener')

function InputController:init(name, inputButtonName, eventEmitter)

    self.eventEmitter = eventEmitter
    self.isPressed = false
    self.name = name
    self.inputButtonName = inputButtonName

end

function InputController:onButtonDown()
    if (self.isPressed) then
        return;
    end

    self.isPressed = true
    self.eventEmitter:emitEvent(self.name .. "Press")
end

function InputController:onButtonUp()
    if (not self.isPressed) then
        return;
    end

    self.isPressed = false
    self.eventEmitter:emitEvent(self.name .. "Release")
    self.eventEmitter:emitEvent(self.name .. "Click")
end

function InputController:addListener(listener)
    self.eventEmitter:addListener(listener)
end

function InputController:onEvent(event)
    if (event.name == (self.inputButtonName .. "In")) then
        self:onButtonDown()
    end

    if (event.name == (self.inputButtonName .. "Out")) then
        self:onButtonUp();
    end
end