---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jameslendrem.
--- DateTime: 21/03/2024 21:18
---

class("Listener").extends()

function Listener:init() end

function Listener:onEvent(event)
    print("Event", event.name)
end