---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jameslendrem.
--- DateTime: 24/03/2024 10:43
---

local pd <const> = playdate
local gfx <const> = pd.graphics

class("View").extends(gfx.sprite)

function View:init(content, params)

    self._defaultParams = {
        borderTopWidth = 0,
        borderBottomWidth = 0,
        borderLeftWidth = 0,
        borderRightWidth = 0,
        paddingTop = 0,
        paddingLeft = 0,
        paddingBottom = 0,
        paddingRight = 0,
        marginTop = 0,
        marginLeft = 0,
        marginBottom = 0,
        marginRight = 0,
        top = 0,
        left = 0,
        color = gfx.kColorBlack,
    }

    self.params = self:inflateParams(params);
    self.content = content;

end

function View:getHeight()

    local height = 0

    height = height + self.params.borderTopWidth
    height = height + self.params.borderBottomWidth
    height = height + self.params.paddingTop
    height = height + self.params.paddingBottom

    --- Just assume content will be text for now.
    local font <const> = gfx.getFont()
    height = height + font:getHeight()

    return height
end

function View:getWidth()

    local width = 0

    width = width + self.params.borderLeftWidth
    width = width + self.params.borderRightWidth
    width = width + self.params.paddingLeft
    width = width + self.params.paddingRight

    --- Just assume content will be text for now.
    local font <const> = gfx.getFont()
    width = width + font:getTextWidth(self.content)

    return width
end

function View:drawView()

    local width <const> = self:getWidth()
    local height <const> = self:getHeight()

    local contentPositionLeft = self.params.borderLeftWidth + self.params.paddingLeft;
    local contentPositionTop = self.params.borderTopWidth + self.params.paddingTop;

    local viewImage = gfx.image.new(width, height);

    gfx.pushContext(viewImage)

    if (self.params.borderTopWidth > 0) then
        gfx.fillRect(0, 0, width, self.params.borderTopWidth)
    end

    if (self.params.borderBottomWidth > 0) then
        gfx.fillRect(0, height - self.params.borderBottomWidth, width, self.params.borderBottomWidth)
    end

    if (self.params.borderLeftWidth > 0) then
        gfx.fillRect(0, 0, self.params.borderLeftWidth, height)
    end

    if (self.params.borderRightWidth > 0) then
        gfx.fillRect(width - self.params.borderRightWidth, 0, width, height)
    end

    gfx.drawText(self.content, contentPositionLeft, contentPositionTop)
    gfx.popContext()

    local topPosition = self.params.top + self.params.marginTop
    local leftPosition = self.params.left + self.params.marginLeft

    self:setImage(viewImage)
    self:moveTo(leftPosition, topPosition)
    self:add()

end

function View:printParams()

    for key, value in pairs(self.params) do
        print(key, ":", value)
    end

end

function View:inflateParams(params)

    local inflatedParams = {};

    for key, value in pairs(self._defaultParams) do
        inflatedParams[key] = value;
    end

    for key, value in pairs(params) do
        inflatedParams[key] = value;
    end

    return inflatedParams;

end

function View:getParams()

    return self.params;

end